# Le retour des promesses

<br/>

### Un paragraphe d'explication

Lorsqu'une erreur se produit, qu'elle provienne d'un flux synchrone ou asynchrone, il est imp√©ratif de disposer d'une trace de pile compl√®te du flux d'erreurs. √âtonnamment, lorsqu'une fonction `async` renvoie une promesse sans `await` (par exemple, elle appelle une autre fonction `async`), si une erreur se produit, la fonction appelante n'appara√Ætra pas dans la trace de la pile. La personne qui diagnostiquera l'erreur ne disposera donc que d'une information partielle - d'autant plus si la cause de l'erreur se situe dans cette fonction d'appel. Il existe une fonctionnalit√© v8 appel√©e "zero-cost async stacktraces" qui permet de ne pas couper les traces de pile sur les `await` les plus r√©cents. Mais sans certaines modalit√©s de mise en ≈ìuvre non n√©gligeables, elle ne fonctionnera pas si la valeur de retour d'une fonction (sync ou async) est une promesse. Donc, pour √©viter les trous dans les traces de pile lorsque des promesses retourn√©es sont rejet√©es, nous devons toujours r√©soudre explicitement les promesses avec `await` avant de les retourner √† partir des fonctions.

<br/>

### Exemple de code incorrect¬†: appel d'une fonction async sans await

<details><summary>Javascript</summary>
<p>

```javascript
async function throwAsync(msg) {
  await null // il faut attendre au moins quelque chose pour √™tre vraiment asynchrone (voir note n¬∞ 2)
  throw Error(msg)
}

async function returnWithoutAwait () {
  return throwAsync('manque returnWithoutAwait dans la trace de pile')
}

// üëé N'aura PAS la fonction returnWithoutAwait dans la trace de pile
returnWithoutAwait().catch(console.log)
```

log re√ßu

```
Error: manque returnWithoutAwait dans la trace de pile
    at throwAsync ([...])
```
</p>
</details>

### Exemple de code¬†: appel d'une fonction async avec await appropri√©

<details><summary>Javascript</summary>
<p>

```javascript
async function throwAsync(msg) {
  await null // il faut attendre au moins quelque chose pour √™tre vraiment asynchrone (voir note n¬∞ 2)
  throw Error(msg)
}

async function returnWithAwait() {
  return await throwAsync('avec toutes les instructions pr√©sentes')
}

// üëç aura la fonction returnWithoutAwait dans la trace de pile
returnWithAwait().catch(console.log)
```

log re√ßu

```
Error: avec toutes les instructions pr√©sentes
    at throwAsync ([...])
    at async returnWithAwait ([...])
```

</p>
</details>

<br/>

### Exemple de code incorrect¬†: retourner une promesse sans marquer la fonction comme async

<details><summary>Javascript</summary>
<p>

```javascript
async function throwAsync () {
  await null // il faut attendre au moins quelque chose pour √™tre vraiment asynchrone (voir note n¬∞ 2)
  throw Error('manque syncFn dans la trace de pile')
}

function syncFn () {
  return throwAsync()
}

async function asyncFn () {
  return await syncFn()
}

// üëé syncFn manquera dans la trace de pile parce qu'elle renverra une promesse alors qu'elle est sync
asyncFn().catch(console.log)
```

log re√ßu

```
Error: manque syncFn dans la trace de pile
    at throwAsync ([...])
    at async asyncFn ([...])
```

</p>
</details>

### Exemple de code¬†: marquer la fonction comme async car elle renvoie une promesse

<details><summary>Javascript</summary>
<p>

```javascript
async function throwAsync () {
  await null // il faut attendre au moins quelque chose pour √™tre vraiment asynchrone (voir note n¬∞ 2)
  throw Error('avec toutes les instructions pr√©sentes')
}

async function changedFromSyncToAsyncFn () {
  return await throwAsync()
}

async function asyncFn () {
  return await changedFromSyncToAsyncFn()
}

// üëç maintenant changedFromSyncToAsyncFn sera pr√©sent dans la trace de la pile
asyncFn().catch(console.log)
```

log re√ßu

```
Error: avec toutes les instructions pr√©sentes
    at throwAsync ([...])
    at changedFromSyncToAsyncFn ([...])
    at async asyncFn ([...])
```

</p>
</details>

<br/>

### Exemple de code incorrect¬†: utilisation directe du rappel async lorsque le rappel sync est attendu

<details><summary>Javascript</summary>
<p>

```javascript
async function getUser (id) {
  await null
  if (!id) throw Error('la trace de pile n\'indique pas l\'endroit o√π getUser a √©t√© appel√©')
  return {id}
}

const userIds = [1, 2, 0, 3]

// üëé la trace de pile aura la fonction getUser mais ne donnera aucune indication sur l'endroit o√π elle a √©t√© appel√©e
Promise.all(userIds.map(getUser)).catch(console.log)
```

log re√ßu

```
Error: la trace de pile n'indique pas l'endroit o√π getUser a √©t√© appel√©
    at getUser ([...])
    at async Promise.all (index 2)
```

*Remarque compl√©mentaire*¬†: on pourrait croire que `Promise.all (index 2)` peut aider √† comprendre l'endroit o√π `getUser` a √©t√© appel√©,
mais en raison d'un [bogue compl√®tement diff√©rent dans la v8](https://bugs.chromium.org/p/v8/issues/detail?id=9023), `(index 2)` est
une ligne interne de v8

</p>
</details>

### Exemple de code¬†: envelopper le rappel async dans une fonction async factice avant de le passer en rappel sync

<details><summary>Javascript</summary>
<p>

*Remarque 1*¬†: si vous contr√¥lez le code de la fonction qui appelle le rappel, changez simplement cette fonction
en async et ajoutez `await` avant l'appel du rappel. Ci-dessous, je suppose que vous n'√™tes pas en charge du code qui appelle
le rappel (ou que son changement est inacceptable, par exemple en raison de la r√©trocompatibilit√©)

*Remarque 2*¬†: tr√®s souvent, l'utilisation du rappel async dans les endroits o√π l'on s'attend √† ce qu'il soit sync ne fonctionnerait pas du tout. Il ne s'agit pas
de savoir comment r√©parer le code qui ne fonctionne pas - il s'agit de savoir comment r√©parer la trace de pile au cas o√π le code fonctionne d√©j√†
comme pr√©vu

```javascript
async function getUser (id) {
  await null
  if (!id) throw Error('avec toutes les instructions pr√©sentes')
  return {id}
}

const userIds = [1, 2, 0, 3]

// üëç maintenant la ligne ci-dessous est dans la trace de la pile
Promise.all(userIds.map(async id => await getUser(id))).catch(console.log)
```

log re√ßu

```
Error: avec toutes les instructions pr√©sentes
    at getUser ([...])
    at async ([...])
    at async Promise.all (index 2)
```

gr√¢ce au `await` explicite dans `map`, la fin de la ligne `at async ([...])` indique l'endroit exact o√π
`getUser` est appel√©

*Remarque compl√©mentaire*¬†: si la fonction async qui enveloppe `getUser` n'a pas `await` avant le retour (exemple incorrect n¬∞1 + exemple incorrect n¬∞3)
alors il ne restera qu'une seule instruction dans la trace de la pile¬†:

```javascript
[...]

// üëé exemple incorrect n¬∞1 + exemple incorrect n¬∞3 - une seule instruction dans la trace de la pile
Promise.all(userIds.map(async id => getUser(id))).catch(console.log)
```

log re√ßu

```
Error: [...]
    at getUser ([...])
```

</p>
</details>

<br/>

## Explication approfondie

Les m√©canismes des traces de piles des fonctions de sync et des fonctions async dans l'impl√©mentation de la v8 sont tr√®s diff√©rents :
La trace de pile sync est bas√©e sur la **pile** fournie par le syst√®me d'exploitation sur lequel tourne Node.js (comme dans la plupart des langages
de programmation). Lorsqu'une fonction async est en cours d'ex√©cution, la **pile** du syst√®me d'exploitation l'a sort d√®s que la
fonction est arriv√©e √† son premier `await`. Donc la trace de pile async est un m√©lange de la **pile** du syst√®me d'exploitation et d'une
**cha√Æne de r√©solution des promesses** rejet√©es. L'impl√©mentation "zero-cost async stacktraces" √©tend la  **cha√Æne de r√©solution des promesses**
uniquement lorsque la promesse est `awaited` <span>[¬π](#1)</span>. Parce que seules les fonctions `async` peuvent `await`,
la fonction sync sera toujours manquante dans la trace de la pile async si une op√©ration async a √©t√© effectu√©e apr√®s que la fonction
a √©t√© appel√© <span>[¬≤](#2)</span>

### Le compromis

Chaque `await` cr√©e une nouvelle micro-t√¢che dans la boucle d'√©v√©nement, donc l'ajout d'autres `await` dans le code
introduit une certaine p√©nalit√© de performance. N√©anmoins, la p√©nalit√© de performance introduite par le r√©seau ou
la base de donn√©es est [√©norm√©ment plus grande](https://colin-scott.github.io/personal_website/research/interactive_latency.html)
donc la p√©nalit√© suppl√©mentaire `await` n'est pas quelque chose qui devrait √™tre consid√©r√© pendant le d√©veloppement de serveurs web ou de CLI
sauf pour un code tr√®s chaud par requ√™te ou commande. Donc, la suppression de `await` dans 
les `return await` devrait √™tre l'un des derniers moyens pour am√©liorer sensiblement les performances
et ne doit absolument pas √™tre fait en amont.


### Pourquoi return await √©tait consid√©r√© comme incorrect dans le pass√©

Un certain nombre d'[excellents articles](https://jakearchibald.com/2017/await-vs-return-vs-return-await/) expliquent
pourquoi `return await` ne devrait jamais √™tre utilis√©e en dehors du bloc `try` et m√™me une
[r√®gle ESLint](https://eslint.org/docs/rules/no-return-await) l'interdit. La raison, c'est que depuis que async/await
est disponible avec des transpileurs dans Node.js 0.10 (et a obtenu un support natif dans Node.js 7.6) et jusqu'√† ce
que "zero-cost async stacktraces" a √©t√© introduit dans Node.js 10 et d√©marqu√© dans Node.js 12, `return await` √©tait absolument
√©quivalent √† `return` pour tout code en dehors du bloc `try`. Il se peut que ce soit encore le cas pour certains autres moteurs ES.
C'est pourquoi la r√©solution des promesses avant de les retourner est la meilleure pratique pour Node.js et non pour EcmaScript en g√©n√©ral

### Remarques¬†:

1. Une autre raison pour laquelle la trace de pile async a une impl√©mentation aussi d√©licate, c'est que la trace de pile
doit toujours √™tre construite de mani√®re synchrone, sur le m√™me rythme que la boucle d'√©v√©nement <span id="a1">[¬π](#1)</span>
2. Sans `await` dans `throwAsync`, le code serait ex√©cut√© dans la m√™me phase de la boucle d'√©v√©nements. C'est un cas
d√©grad√© o√π la **pile** de l'OS ne serait pas vide et la trace de pile serait pleine m√™me sans attendre
explicitement le r√©sultat de la fonction. Habituellement, l'utilisation des promesses inclut des op√©rations asynchrones
et des parties de la trace de la pile sont perdues
3. Zero-cost async stacktraces ne fonctionnera toujours pas pour les usages compliqu√©s de la promesse, par exemple la promesse unique
attendue √† plusieurs reprises dans diff√©rents endroits

### R√©f√©rences¬†:
  <span id="1">1. </span>[article de blog sur zero-cost async stacktraces en v8](https://v8.dev/blog/fast-async)
  <br/>

  <span id="2">2. </span>[Document sur zero-cost async stacktraces avec les d√©tails de mise en ≈ìuvre mentionn√©s ici](
    https://docs.google.com/document/d/13Sy_kBIJGP0XT34V1CV3nkWya4TwYx9L3Yv45LdGB6Q/edit
  )
  <br/>
